version: "3.3"

services:
  app:
    container_name: z-mirror
    build:
      context: .
      dockerfile: Dockerfile
    command: bash start.sh
    restart: on-failure
    ports:
      - "3050:3050"
      - "3001:3001"
